# Branch Protection Rules for Silent Forge Engine

# Main branch protection
main:
  required_status_checks:
    strict: true
    contexts:
      - build-and-test
      - format
      - lint
  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
    require_code_owner_reviews: true
  enforce_admins: true
  required_linear_history: true
  allow_force_pushes: false
  allow_deletions: false

# New-main branch protection
new-main:
  required_status_checks:
    strict: true
    contexts:
      - build-and-test
      - format
      - lint
  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
  enforce_admins: true
  required_linear_history: true
  allow_force_pushes: false
  allow_deletions: false

# Develop branch protection
develop:
  required_status_checks:
    strict: true
    contexts:
      - build-and-test
      - format
  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
  enforce_admins: true
  required_linear_history: true
  allow_force_pushes: false
  allow_deletions: false 